# Generated by Django 5.2.1 on 2026-01-17 00:26

import django.db.models.deletion
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Roboczy'), ('sent', 'Wysłano'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono')], default='draft', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('client_address', models.TextField(blank=True)),
                ('roof_type', models.CharField(choices=[('gable', 'Dwuspadowy'), ('hip', 'Kopertowy'), ('mansard', 'Mansardowy'), ('flat', 'Płaski')], default='gable', max_length=20)),
                ('plan_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('real_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pitch_angle', models.IntegerField(default=35)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('obstacles', models.JSONField(blank=True, default=list)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=quotes.models.quote_image_path)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=quotes.models.quote_image_path)),
                ('ai_extracted_data', models.JSONField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_processing', models.BooleanField(default=False)),
                ('materials_breakdown', models.JSONField(blank=True, default=dict)),
                ('margin_percent', models.IntegerField(default=35)),
                ('vat_rate', models.IntegerField(default=23)),
                ('total_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
