# Generated by Django 5.2.1 on 2026-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='gasior_elements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='gutter_system',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='roof_measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
