# Generated by Django 5.2.1 on 2026-01-20 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Publiczny UUID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('processing', 'Przetwarzanie'), ('completed', 'Zakończony'), ('failed', 'Błąd'), ('contacted', 'Skontaktowano'), ('converted', 'Skonwertowany')], default='pending', max_length=20, verbose_name='Status')),
                ('uploaded_file', models.FileField(upload_to='leads/uploads/%Y/%m/', verbose_name='Plik')),
                ('file_type', models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('pdf', 'PDF')], max_length=10, verbose_name='Typ pliku')),
                ('roof_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ dachu')),
                ('pitch_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kąt nachylenia (°)')),
                ('roof_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Powierzchnia dachu (m²)')),
                ('dimensions', models.JSONField(blank=True, null=True, verbose_name='Wymiary')),
                ('roof_elements', models.JSONField(blank=True, null=True, verbose_name='Elementy dachu')),
                ('ai_raw_response', models.JSONField(blank=True, null=True, verbose_name='Surowa odpowiedź AI')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pewność AI (%)')),
                ('ai_warnings', models.JSONField(blank=True, null=True, verbose_name='Ostrzeżenia AI')),
                ('estimated_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Szacowana cena od (PLN)')),
                ('result_pdf', models.FileField(blank=True, null=True, upload_to='leads/pdfs/%Y/%m/', verbose_name='PDF z wynikami')),
                ('processing_error', models.TextField(blank=True, null=True, verbose_name='Błąd przetwarzania')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID zadania Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Rozpoczęcie przetwarzania')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zakończenie przetwarzania')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki handlowca')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data kontaktu')),
                ('contacted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontaktował')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leady',
                'ordering': ['-created_at'],
            },
        ),
    ]
