# Generated by Django 5.2.1 on 2026-01-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_assigned_to_lead_source'),
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='widget_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='widget.widgetconfig', verbose_name='Konfiguracja Widgetu'),
        ),
        migrations.AddField(
            model_name='lead',
            name='widget_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadane widgetu'),
        ),
    ]
