# Generated by Django 5.2.1 on 2026-01-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('metal_tile', 'Blachodachówka'), ('ceramic', 'Dachówka ceramiczna'), ('bitumen', 'Papa'), ('metal_sheet', 'Blacha trapezowa')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waste_factor', models.DecimalField(decimal_places=2, default=1.12, max_digits=4)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
